

CREATE TABLE shop (

	PRODUCTID int IDENTITY(10000,1) primary key NOT NULL, --商品ID
	PRODUCTNAME NVARCHAR(50) NOT NULL, --商品名稱
	PRODUCTIMG NVARCHAR(MAX) NULL, --照片
	PRODUCTPRICE int NULL, --價格
	PRODUCTINTRODUCE NVARCHAR(MAX) NULL, --詳細介紹
	PRODUCTTYPE NVARCHAR(20) NULL, --分類
	PRODUCTQUANTITY int NULL --剩餘數量
);

select * from shop;

--drop table shop



insert into shop(PRODUCTNAME,PRODUCTPRICE,PRODUCTINTRODUCE,PRODUCTTYPE,PRODUCTQUANTITY)
values ('狗狗',100,'這是狗狗','狗狗',100);
insert into shop(PRODUCTNAME,PRODUCTPRICE,PRODUCTINTRODUCE,PRODUCTTYPE,PRODUCTQUANTITY)
values ('貓咪',200,'這是卯咪','貓咪',100);
insert into shop(PRODUCTNAME,PRODUCTPRICE,PRODUCTINTRODUCE,PRODUCTTYPE,PRODUCTQUANTITY)
values ('老鼠',300,'吱吱','老鼠',100);
insert into shop(PRODUCTNAME,PRODUCTPRICE,PRODUCTINTRODUCE,PRODUCTTYPE,PRODUCTQUANTITY)
values ('笨狗',400,'醜狗一條','狗狗',100);
insert into shop(PRODUCTNAME,PRODUCTPRICE,PRODUCTINTRODUCE,PRODUCTTYPE,PRODUCTQUANTITY)
values ('老鼠老鼠',500,'老鼠','老鼠',100);




